repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
