os: linux
dist: xenial
language: python
python: 3.7

install:
  - pip install -e ".[test]"

script: pytest tests

jobs:
  include:
    - stage: formatting
      name: black
      install:
        - pip install black
      script:
        - black --check .
    - stage: formatting
      name: isort
      install:
        - pip install "isort[pyproject]"
      script:
        - isort --check-only

    - stage: packaging
      name: "Python sdist installation"
      install: skip
      script:
        - python setup.py sdist
        - pip install dist/*.tar.gz

    - stage: test

    - stage: deploy
      if: tag IS present AND repo = cmla/plyflatten
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: carlodef
          password:
            - YOUR_PASSWORD_HERE
          distributions: sdist
          on:
            tags: true
